#!/bin/bash

# Retrieve all lists and get an Id
RESULT=$(curl -i -X GET -b cookie-jar http://info3103.cs.unb.ca:24842/lists)
id=$(echo $RESULT | python -c "import sys, json; print json.load(sys.stdin)['list']['id']")

# Create new item
curl -i -H "Content-Type: application/json" -X POST -d '{"title": "Test Item, Please Ignore", "description": "The cake is a lie"}' "http://info3103.cs.unb.ca:24842/lists/$id"

# Retrieve all items and get an Id
RESULT=$(curl -i -X GET -b cookie-jar http://info3103.cs.unb.ca:24842/lists/$id)
id=$(echo $RESULT | python -c "import sys, json; print json.load(sys.stdin)['items']['id']")

# Retrieve an item
curl -i -X GET -b cookie-jar "http://info3103.cs.unb.ca:24842/list/$id/$item"

# Update an item
curl -i -X PUT -d '{"title": "Testing", "description": "For the people who are, still alive"}' -b cookie-jar "http://info3103.cs.unb.ca:24842/list/$id/$item"

# Remove an item
curl -i -X DELETE -b cookie-jar "http://info3103.cs.unb.ca:24842/list/$id/$item"