#!/bin/bash

# Create new list
if [[ $(curl -w "%{http_code}" -s -i -H "Content-Type: application/json" -X POST -d '{"title": "Aperture Laboratories", "description": "There is testing to be done"}' -k https://info3103.cs.unb.ca:24842/lists) == "201" ]]; 
then 
    echo "Successfully created new list"; 
else
    echo "Failed to create new list";
fi;

# Retrieve all lists and get an Id
RESULT=$(curl -w "%{http_code}" -s -i -X GET -b cookie-jar -k https://info3103.cs.unb.ca:24842/lists)
id=$(echo $RESULT | python -c "import sys, json; print json.load(sys.stdin)['lists']['id']");

printf "\nDebug for listClient list retrieval\n\n" > testing.log
echo $RESULT >> testing.log

# Retrieve a list
if [[ $(curl -w "%{http_code}" -s -i -X GET -b cookie-jar -k "https://info3103.cs.unb.ca:24842/list/$id") == "201" ]]; 
then 
    echo "Successfully to retrieve list"; 
else
    echo "Failed to retrieve list";
fi;

# Remove a list
if [[ $(curl -w "%{http_code}" -s -i -X DELETE -b cookie-jar -k "https://info3103.cs.unb.ca:24842/list/$id") == "201" ]]; 
then 
    echo "Successfully removed the list"; 
else
    echo "Failed to remove the list";
fi;