#!/bin/bash

# Create new list
curl -i -H "Content-Type: application/json" -X POST -d '{"username": "'$username'", "password": "'$password'"}' http://info3103.cs.unb.ca:24842/lists

# Retrieve all list and get an Id
RESULT=$(curl -i -X GET -b cookie-jar http://info3103.cs.unb.ca:24842/lists)
id=$(echo $RESULT | cut -f1 ) # Needs formatting

# Retrieve a list
curl -i -X GET -b cookie-jar "http://info3103.cs.unb.ca:24842/list/$id"

# Remove a list
curl -i -X DELETE -b cookie-jar "http://info3103.cs.unb.ca:24842/list/$id"