#!/bin/bash

# Create new list
curl -i -H "Content-Type: application/json" -X POST -d '{"title": "Aperture Laboratories", "description": "There is testing to be done"}' http://info3103.cs.unb.ca:24842/lists

# Retrieve all lists and get an Id
RESULT=$(curl -i -X GET -b cookie-jar http://info3103.cs.unb.ca:24842/lists)
id=$(echo $RESULT | python -c "import sys, json; print json.load(sys.stdin)['lists']['id']")

# Retrieve a list
curl -i -X GET -b cookie-jar "http://info3103.cs.unb.ca:24842/list/$id"

# Remove a list
curl -i -X DELETE -b cookie-jar "http://info3103.cs.unb.ca:24842/list/$id"