#!/bin/bash

# Read username and password
read -p "username: " username
read -s -p "password: " password

# substitute into the curl command
if [[ $(curl -w "%{http_code}" -s -H "Content-Type: application/json" -X POST -d '{"username": "'$username'", "password": "'$password'"}' -c cookie-jar -k https://info3103.cs.unb.ca:24842/signin) =~ .*201 ]]; 
then 
    echo "User successfully created"; 
else
    echo "Failed to create user";
fi;

# Login
if [[ "$(curl -w "%{http_code}" -s -i -X GET -b cookie-jar -k https://info3103.cs.unb.ca:24842/signin)" =~ .*201 ]]; 
then 
    echo "User successfully retrieved"; 
else
    echo "Failed to login user";
fi;


# Logout
if [[ "$(curl -w "%{http_code}" -s -i -X DELETE -b cookie-jar -k https://info3103.cs.unb.ca:24842/signin)" =~ .*201 ]]; 
then 
    echo "User successfully logged out"; 
else
    echo "Failed to logout user";
fi;


# Login again
if [[ "$(curl -w "%{http_code}" -s -i -X GET -b cookie-jar -k https://info3103.cs.unb.ca:24842/signin)" =~ .*201 ]]; 
then 
    echo "User successfully logged in"; 
else
    echo "Failed to login user";
fi;
