#!/bin/bash

# Read username and password
read -p "username: " username
read -s -p "password: " password

# substitute into the curl command
if [[ "$(curl -s -i -H 'Content-Type: application/json' -X POST -d '{'username': '$username', 'password': '$password'}' -c cookie-jar -k https://info3103.cs.unb.ca:24842/signin)" != "201" ]]; 
then 
    echo "User successfully created"; 
else
    echo "Failed to create user"
fi;

# Login
if [[ "$(curl -s -i -X GET -b cookie-jar http://info3103.cs.unb.ca:24842/signin)" != "201" ]]; 
then 
    echo "User successfully created"; 
else
    echo "Failed to create user"
fi;


# Logout
if [[ "$(curl -s -i -X DELETE -b cookie-jar http://info3103.cs.unb.ca:24842/signin)" != "201" ]]; 
then 
    echo "User successfully created"; 
else
    echo "Failed to create user"
fi;


# Login again
if [[ "$(curl -s -i -X GET -b cookie-jar http://info3103.cs.unb.ca:24842/signin)" != "201" ]]; 
then 
    echo "User successfully created"; 
else
    echo "Failed to create user"
fi;
