#!/bin/bash

# Read username and password
read -p "username: " username
read -s -p "password: " password

# substitute into the curl command
if [[ $(curl -w "STATUS:%{http_code}" -s -H "Content-Type: application/json" -X POST -d '{"username": "'$username'", "password": "'$password'"}' -b cookie-jar -c cookie-jar -k https://info3103.cs.unb.ca:24842/signin) =~ .*STATUS:201 ]]; 
then 
    echo "User successfully created"; 
else
    echo "Failed to create user";
fi;

# Login
if [[ "$(curl -w "STATUS:%{http_code}" -s -i -X GET -c cookie-jar -b cookie-jar -k https://info3103.cs.unb.ca:24842/signin)" =~ .*STATUS:200 ]]; 
then 
    echo "User successfully retrieved"; 
else
    echo "Failed to login user";
fi;


# Logout
if [[ "$(curl -w "STATUS:%{http_code}" -s -i -X DELETE -c cookie-jar -b cookie-jar -k https://info3103.cs.unb.ca:24842/signin)" =~ .*STATUS:200 ]]; 
then 
    echo "User successfully logged out"; 
else
    echo "Failed to logout user";
fi;

# Login Again
if [[ $(curl -w "STATUS:%{http_code}" -s -H "Content-Type: application/json" -X POST -d '{"username": "'$username'", "password": "'$password'"}' -b cookie-jar -c cookie-jar -k https://info3103.cs.unb.ca:24842/signin) =~ .*STATUS:201 ]]; 
then 
    echo "User successfully created"; 
else
    echo "Failed to create user";
fi;
